!
! ce chk
!
*if,arg1,gt,.3,then
immed,1
/UIS,MSGPOP,0
CECHK
/UIS,MSGPOP,2
et,88,33
type,88
RLON
*do,cenum,arg1,arg2,arg3
nsel,s,ce,,cenum
*get,n1,node,,num,max
*get,loops,node,,count
*get,n2,node,n1,nxtl
real,cenum
*do,el,1,loops-1
e,n1,n2
*get,n2,node,n2,nxtl
*enddo
*enddo
n1=
loops=
el=
n2=
beep
*else
/uis,msgpop,1
*msg,note
USAGE: CE_CHK,BEGIN CE #, ENDING CE # , # of DOF
/UIS,MSGPOP,2
*ENDIF

