!
!  macro hpgl:  makes hpgl file of current plot
!
!parsav
!*ask,NEW FILENAME FOR HPGL FILE,'AAA.HPGL'
/sys,rm hpgl.plot
*GET,PTYPE,GRAPH,1,TYPE
*IF,PTYPE,GT,4,then
/TYPE,ALL,4
*endif
/show,hpgl,plot,1   	!	assumes vector b&w plot
/replo
/show,_junk_
/show,term
/sys,f33-hpgl hpgl.plot
!*ask,nname,New hpgl file name,'A.hpgl'
!/syp,mv hpgl00.grph,nname,%aa%
!/sys,applix43 /users/abmo01t/axhome/start.ag &
!/sys,applix43 A.hpgl &
/sys,mv hpgl00.grph A.hpgl
/sys,applix43 -add A.hpgl &

