! flips elements so that selected node set are the "i" nodes
/nopr
/anno,dele
*cfopen,adfkj
enode
!ersel,stif,40
*GET,NNODES,NODE,,COUNT
ND=NDNEXT(0)
*DO,LOOP,1,NNODES
elem=enextn(nd,1)
inode=nelem(elem,1)
*if,inode,eq,nd,then
!*cfwrit,/tspec,8,
!*cfwrit,/AN3D,TEXT,nx(nd),ny(nd),nz(nd),'I'
*else
!*cfwrit,/tspec,12
!*cfwrit,/AN3D,TEXT,nx(nd),ny(nd),nz(nd),'O'
emod,elem,-1,nelem(elem,2),nelem(elem,1)
*endif
ND=NDNEXT(nd)
*enddo
*cfwrit,/tspec
*cfclos
/inp,adfkj
/tspec
)/gopr



