/nopr                                                                           
!
!    ldon.mac  A macro to turn on line direction 
!              arrows on.
!
/psym,ldir,1                                                                    
/repl                                                                           
/gopr                                                                           
