!
!                   macwin.mac
!
!	A macro to setup the windows when viewing
!                  the fuel manifold model.
!
/nopr
/win,1,-1,.5,-1,0                                                               
/win,2,-1,.5,0,1                                                                
/win,3,.5,1,-1,1                                                                
/view,1,1,1,1
/view,2,
/view,3,1
/auto,1
rp3,1
/type,1,4
rp3,1
/gopr

