!
! plaatt.mac  plots area attributes
!
/ANNO,DELE
/gsav,temp
/reset
/type,1,
/plopts,leg1,off
/tspec,12,1,1,,,,
,INFO,OFF
,leg2,off
,leg3,off
,VERS,OFF
/vup,1,x
/wind,1,ltop,
/pnum,area,1
/tspec,12,1,1,,,,
/tlab,-.5,.9,AREA #'S
/TLAB,DELE
eplo
noeras
/wind,1,rtop,
eton
eplo
/tspec,12,1,1
/TLAB,.5,.9,TYPES
/TLAB,DELE
/wind,1,lbott,
rlon
eplo
/TLAB,-.5,-.9,REALS
/wind,1,rbott
mpon
eplo
/TLAB,.5,-.9,MATLS
/erase
!/gresum,temp
/gopr


