/win,1,top                                                                      
/win,2,bot                                                                      
/view,1,,-1                                                                     
/view,2,,1                                                                      
/auto,1                                                                         
/auto,2                                                                         
