!
! macro xshift  moves set of selected nodes to the max or min x value 
!	of any node in the set.  Good for temperature interpolation
!
/pmacro
parsav
cm,_temp_,node
MODMSH,noch
SHPP,OFF
*msg,note
Select set of nodes you want to move
beep
nsel,r,p
*ask,mxormin,Move nodes to min (0) or max (1) value of those selected?,0
*IF,mxormin,GT,0,THEN
*GET,NEWX,NODE,,MXLOC,X
*ELSE
*GET,NEWX,NODE,,MNLOC,X
*ENDIF
NMOD,ALL,NEWX,,,,,
cmsel,,_temp_
cmdele,_temp_
PARRES

